name: Build, Push, Deploy
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.set_image.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: List Files
        run: ls -la
      - name: Build and push
        id: build
        working-directory: ./app
        run: |
          REPO="${{ steps.ecr.outputs.registry }}/${{ github.repository_owner }}/hello"
          IMAGE="${REPO}:${{ github.sha }}"
          docker build -t "$IMAGE" -f Dockerfile
          # docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
      - name: Set output
        id: set_image
        run: echo "::set-output name=image_uri::${{ steps.build.outputs.image }}"
